FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG VERSION=dev
RUN CGO_ENABLED=0 go build \
    -ldflags "-s -w -X github.com/projectdiscovery/vulnx/v2/cmd/vulnx/clis.Version=${VERSION}" \
    -o vulnx cmd/vulnx/main.go

FROM alpine:3.18.2
RUN apk -U upgrade --no-cache \
    && apk add --no-cache bind-tools ca-certificates
COPY --from=builder /app/vulnx /usr/local/bin/

ENTRYPOINT ["vulnx"]
